version: '3'
services:
    webapp:
      container_name: ${CONTAINER_NAME}
      image: ghcr.io/19-mrx-98/tkf_webapp_v2-latest
      volumes:
        - ${APACHE_DIR_DEV}:/var/www/html
        - ${APACHE_CONF_FILE}:/etc/apache2/apache2.conf
        - ${APP_LOG_DIR}:/var/www/html/logs
      ports:
        - ${STD_WEBSRV_PORT}:80
        - ${SSL_WEBSRV_PORT}:443
      restart: always
